public class DemoJava {
    public static void main(String []args) {
       // Small int a, and b
       int a;
       int b;
       // inputs that equal
       a = 10;
       b = 20;
       
       System.out.println("Value of a = " + a);
       System.out.println("Value of b = " + b);
       
       System.out.println("Value of a = " + a + "and value of b" + b);
    }
}

// Demonstrates declaring variables a and b
