public class TicTacToeApp {
    public static void main(String[] args) {
        Player p1 = new Player();
        Player p1 = new BetterPlayer();
        playertheGame(p1, p2);
  }
  public static void playTheGame(Player p1, Player p2) {
        p1.move();
        p2.move();
  }
  private static void playtheGame(Player p1, Player p2) {
       throw new UnsupportedOperationException("Not supported yet");
  }
}
